version: '3'
services:

  backend:
    build: 
      dockerfile: ./docker/backend.Dockerfile
      context: .
    ports:
      - 8081:80
    depends_on:
      - mongo
  
  frontend:
    build: 
      dockerfile: ./docker/frontend.Dockerfile
      context: .
    ports:
      - 80:80

  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: yourName
      MONGO_INITDB_ROOT_PASSWORD: yourP@ssw0rd


